[project]
name = "langgraph-gmail"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jasmin Pomasoncco", email = "jasminpomasoncco@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "google-api-python-client>=2.200.0",
    "google-auth-httplib2>=0.4.2",
    "google-auth-oauthlib>=1.4.1",
    "pydantic>=2.13.5",
]

[project.scripts]
langgraph-gmail = "langgraph_gmail:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
